[package]
name = "iceoryx2"
description = "iceoryx2: Lock-Free Zero-Copy Interprocess Communication"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = "../README.md"
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[features]
# Enables https://crates.io/crates/log as default logger
logger_log = ["iceoryx2-bb-log/logger_log"]
# Enables https://crates.io/crates/tracing as default logger
logger_tracing = ["iceoryx2-bb-log/logger_tracing"]
# The permissions of all resources will be set to read, write, execute for everyone.
# This shall not be used in production and is meant to be enabled in a docker environment
# with inconsistent user configuration.
dev_permissions = ["iceoryx2-cal/dev_permissions"]

[dependencies]
iceoryx2-bb-container = { workspace = true }
iceoryx2-bb-derive-macros = { workspace = true }
iceoryx2-bb-system-types = { workspace = true }
iceoryx2-bb-lock-free = { workspace = true }
iceoryx2-bb-log = { workspace = true }
iceoryx2-bb-memory = { workspace = true }
iceoryx2-bb-posix = { workspace = true }
iceoryx2-bb-elementary = { workspace = true }
iceoryx2-cal = { workspace = true }
iceoryx2-pal-concurrency-sync = { workspace = true }

lazy_static = { workspace = true }
serde = { workspace = true }
cdr = { workspace = true }
toml = { workspace = true }
sha1_smol = { workspace = true }
tiny-fn = { workspace = true }

[dev-dependencies]
iceoryx2-bb-testing = { workspace = true }
generic-tests = { workspace = true }
