name: Miri

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, release* ]

jobs:
  miri:
    name: "Miri"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
      - name: Test with Miri
        run: |
          # the script will be run at the project root, so use filename directly
          filename=".miri_allowlist"
          while IFS= read -r line; do
            if [[ "$line" == \#* ]]; then
              echo "$line"
              continue
            fi          
            if [[ -d $line ]]; then
              cd "$line" || { echo "Failed to change directory to $line"; exit 1; }
              echo "Run cargo miri test under: $(pwd)"
              cargo miri test
              cd -
            else
              echo "$line is not a valid directory."
            fi
          done < "$filename"        
        
  